//------------------------------------------------------------------------------
// <auto-generated>
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Globalization;

namespace ESEIM.Models
{
    [Table("LMS_LECTURE_MANAGEMENT")]
    public class LmsLectureManagement
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string LectName { get; set; }
        public string LectCode { get; set; }
        public string LectDescription { get; set; }
        public int? Duration { get; set; }
        public string Status { get; set; }
        public string Unit { get; set; }
        public string SubjectCode { get; set; }
        public string VideoPresent { get; set; }
        public string VideosDuration
        {
            get
            {
                return JsonConvert.SerializeObject(ListVideoDuration);
            }
            set
            {
                ListVideoDuration = string.IsNullOrEmpty(value)
                ? new List<VideoDuration>()
                : JsonConvert.DeserializeObject<List<VideoDuration>>(value);
            }
        }
        [NotMapped]
        public List<VideoDuration> ListVideoDuration { get; set; }
    }
    public class VideoDuration
    {
        public string VideoFileCode { get; set; }
        public int Duration { get; set; }
    }
}

