//------------------------------------------------------------------------------
// <auto-generated>
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ESEIM.Models
{
    [Table("LMS_SUBJECT_MANAGEMENT")]
    public class LmsSubjectManagement
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }
        public string SubjectName { get; set; }
        public string SubjectCode { get; set; }
        public string SubjectDescription { get; set; }
        public string Teacher { get; set; }
        public string Author { get; set; }
        public int? Duration { get; set; }
        public string Unit { get; set; }
        public string ImageCover { get; set; }
        public string VideoPresent { get; set; }
        public string FileBase { get; set; }
        public string Status { get; set; }
        public string CourseCode { get; set; }
    }
}

